# Generated by Django 4.2 on 2023-04-27 07:26

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=reviews.models.PathAndRename('static/images/')),
        ),
    ]
